use_frameworks!
platform :ios, '15.0'

target 'engram' do
  pod 'KeychainAccess'
end

target 'engram WatchKit App' do
  platform :watchos, '7.2'
end

target 'engram WatchKit Extension' do
  platform :watchos, '7.2'
  pod 'KeychainAccess'
end

target 'Send to engram' do
  pod 'KeychainAccess'
end
